import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import { getServerSession } from "next-auth";
import AuthProvider from "@/providers/SessionProvider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Projeto Mel",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession();

	return (
		<html lang="pt">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ConfigProvider wave={{ disabled: true }}>
					{session ? (
						<AuthProvider session={session}>
							{children}
						</AuthProvider>
					) : (
						<>{children}</>
					)}
				</ConfigProvider>
			</body>
		</html>
	);
}
